export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e8e9",
        outline: "#747878",
        secondary: "#735c00",
        "warning-amber": "#B45309",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "inverse-primary": "#c8c6c5",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed": "#1c1b1b",
        "mist-grey": "#E5E7EB",
        "primary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#e9c349",
        "surface-tint": "#5f5e5e",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#574500",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed65b",
        "gold-metallic-end": "#F9E29C",
        "on-tertiary-fixed-variant": "#36485b",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#474746",
        "surface-bright": "#f8f9fa",
        "on-tertiary-container": "#73869a",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed": "#091d2e",
        "primary-fixed-dim": "#c8c6c5",
        "outline-variant": "#c4c7c7",
        "on-primary-container": "#858383",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#241a00",
        "tertiary-container": "#091d2e",
        "on-background": "#191c1d",
        "success-teal": "#0D9488",
        "inverse-surface": "#2e3132",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "gold-metallic-start": "#D4AF37",
        "tertiary-fixed": "#d1e4fb",
        "secondary-fixed": "#ffe088",
        background: "#f8f9fa",
        "tertiary-fixed-dim": "#b5c8df",
        "on-primary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "error-container": "#ffdad6",
        "surface-dim": "#d9dadb",
        tertiary: "#000000",
        surface: "#f8f9fa",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#444748",
        "on-secondary-container": "#745c00",
        "primary-container": "#1c1b1b",
        primary: "#000000",
      },
      spacing: {
        "margin-mobile": "1rem",
        "section-gap": "5rem",
        "margin-desktop": "2.5rem",
        gutter: "1.5rem",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "body-lg": ["IBM Plex Sans Arabic", "sans-serif"],
        "label-bold": ["IBM Plex Sans Arabic", "sans-serif"],
        "display-lg": ["IBM Plex Sans Arabic", "sans-serif"],
        "body-md": ["IBM Plex Sans Arabic", "sans-serif"],
        "headline-sm": ["IBM Plex Sans Arabic", "sans-serif"],
        "display-lg-mobile": ["IBM Plex Sans Arabic", "sans-serif"],
        "headline-md": ["IBM Plex Sans Arabic", "sans-serif"],
        "stats-number": ["IBM Plex Sans Arabic", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "display-lg": [
          "48px",
          { lineHeight: "60px", letterSpacing: "0", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "40px", fontWeight: "700" },
        ],
        "headline-md": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "stats-number": ["36px", { lineHeight: "44px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
