import { MY_SPACE_IMAGES } from "@website/constants/mySpaceImages";
import { EDITOR_IMAGE_FALLBACKS } from "@website/constants/editorImages";
import { ADMIN_IMAGES } from "@admin/constants/adminImages";

export const SITE_LOGO =
  "https://lh3.googleusercontent.com/aida-public/AB6AXuCwETDnAo27sVhZY3SpgYYKHTPluKhVuATAx-x-dXjXJ2Fkzz7dVQs_O6E-c2Oufpvm3GYVD3AaWTIaQK3qZ3eXlDW26IokpTj-D6Rkczmk262u9ShWNwFOOL7S3hrVlvSc7rv20lsoT2pwDUlG33e1ZrhmH0cBtRxcf5s_Nx2HxLp44bL5OapAfrJdvz0_4ymjonP_BrN1TvRrSupFV-woNwbvHZ0hr1YgyKdrcKLJ-yXgqVYdIvGMSIm7WMMkvqsufz8sFO7yYT_E";

export const SIDEBAR_LOGO =
  "https://lh3.googleusercontent.com/aida-public/AB6AXuBiuuen2nW5koVNiLbr94FfARPuJTOoQVCsSK-mHbsBAFJBK-_xEJa6oQU4keZaiKO8e5MuCaRDIdUfVc5YrJUySy_Gys6uXz-62vtRcsrGQOSLKuwayXWrEsj3emKzxozffXEzEN6HZZHeWyHwLESwEczMSkGf90v1Ooj1Pxs8ZStABavDYWax4ePyMwk4I0MFKzkLEzNqfXydkoQfz8UunmWn4BSvkJE9nocsiUt6KPGeKPhkY_Q1KTXTkdMrZsaViMk6Pu5pjw_b";

export const USER_AVATAR =
  "https://lh3.googleusercontent.com/aida-public/AB6AXuBoRV3-wJrJyUPADb71n0yOCT9ObL0ydQqAIWjRn7QHYO_krhlxfY4C0HXKvBHL2LKzEybZAUC5aSqYwBhFSfDUl04zsgP04-1NHS6Nxm5bh-gMXNLAgiB4U8EXYABDt2W7AfJmXIgb6wMnehIcmUI5veojBVrLbwbqFQ4-5nUmuLG4EZbnIHyaRH3Xn3QwL1lzfVSvxt8QVVVXY6LjrYsEKUEgT4rT_fhyCHVi5LkXbnO9hd8Gc9bRe5J7VQPdICswKzENeZe5GijO";

export const STORIES_ANALYST_AVATAR =
  "https://lh3.googleusercontent.com/aida-public/AB6AXuC2UOqtARbAyBFySjnSO-p8krR565iBvGoCgg5Nes0R31EGNnq17BG0_eXYVGKFaezBgGoWxf-MOANDRvAzm602SQ7gwOV112kMAIeoS8WRu4VICX0U-_a7oElIso-8rFXpQDdMrx0o14ZTf7XuybVj9VTKTVoGCf4hdORZsLz2T_K3_vP0hxBXI6SxVpQeCvuRIPA4dG6w_q3_Dmwymt0kg6gdLX1hcDH86YZ_XpC-xZW9xbA8TJ2SrsHK2vIDHbcbACkj87ErOd0g";

export const PODCAST_ANALYST_AVATAR =
  "https://lh3.googleusercontent.com/aida-public/AB6AXuC__OEo-i8xbWIdfXo6nefgqFdWTGBu-abOmZJ29m6a3XqLVtXDACus2mD69LC_Un7MznQcrTkhGoFUgtqLJBhM0qVr7CGgJuAaFIAAjZmc1UWpid1WRYhZMUSnTnAoo3knKd3XDSuAGGnAroyy_ZzQZXhVgyeyPDwbyz-CR91z5hFAv-ZuMP9fJmFzdspX6fVSMhngHbBCDf3HSnd4hKw6wRGsKoWSlDZft5F8UXW7mNCblWw-JvLLTfu6hyzoEPSTeHD4uFM6wyA0";

export const MEDIA_LITERACY_AVATAR =
  "https://lh3.googleusercontent.com/aida-public/AB6AXuCX_Vhgk33EpTrlPi2qzLgKayvyyafGCUMNeUw8Dr9w1x23s33mDGnRrGXwmxy4dCJ99STKzbXpbAxjHWWyRPHXRJvW4M5lnGUjbgIEY0TBZQokz3ANRE0e2cOJYD94QrCjS4GOX7vp8D3n3A8hofxjsBR4L_NlaSb2FuCX7uA4BORbshMOLLrLnRikfeh8qBNDZt4qbLF1cvglDuTI2DxhDKl52eC6kRoNjQXl-qeWuFp4UJvTECsosqBrk5HIl1SfIK-84Z54fzcr";

export const TERMINOLOGY_AVATAR =
  "https://lh3.googleusercontent.com/aida-public/AB6AXuAhWEYC_ZYe6CXegMqOBFY9536B0vNd6VRDjYfYKYlpnJVO_Fn5Ry4mkcwWjirqMv28bQeKA0rsjZZci30reL-9I4MPLQPU0k6naNzhW0bJYjC9a1LZ80aJ1mbhEmQFQO1Q9NKnlsugFH9mqTwfRDiJ3qXH3J4REj-MGUt4l6zWYmxFUQ2rI9v_C5_5hSarQsWAl_9dd-9kCU32IyvgNIGe3T2cESJKh7zHt5NZBicV8SnPy0YstU7h0toqI67CE4PjgQRqsW2F_UyL";

export const TERMINOLOGY_ASSISTANT_AVATAR = TERMINOLOGY_AVATAR;

export const VERIFIED_NEWS_AVATAR = TERMINOLOGY_AVATAR;

export const MY_SPACE_NAV_AVATAR = MY_SPACE_IMAGES.navAvatar;
export const MY_SPACE_PROFILE_AVATAR = MY_SPACE_IMAGES.userAvatar;

export const EDITOR_NAV_AVATAR = EDITOR_IMAGE_FALLBACKS.navAvatar;
export const EDITOR_ARTICLE_IMAGE = EDITOR_IMAGE_FALLBACKS.articleImage;

export const ADMIN_NAV_AVATAR = ADMIN_IMAGES.navAvatar;
